services:
  app:
    image: ghcr.io/overklassniy/stankin_antispam_bot:latest
    pull_policy: always
    container_name: stankin-antispam
    user: root
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "12523:12523"
    restart: unless-stopped