services:
  app:
    image: ghcr.io/overklassniy/stankin_antispam_bot:latest
    pull_policy: always
    container_name: stankin-antispam
    user: root
    env_file: .env
    network_mode: host
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped